CREATE SCHEMA SENAINOTES;

CREATE TABLE SENAINOTES.USUARIO (
		ID_USUARIO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		EMAIL TEXT NOT NULL UNIQUE,
		SENHA TEXT NOT NULL,
		FLAG_DARK_MODE BOOLEAN,
		DATA_CADASTRO TIMESTAMPTZ NOT NULL
);

CREATE TABLE SENAINOTES.TAG(
		ID_TAG INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		NOME TEXT NOT NULL
);


CREATE TABLE SENAINOTES.ANOTACAO(
		ID_ANOTACAO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		ID_USUARIO  INT NOT NULL REFERENCES SENAINOTES.USUARIO(ID_USUARIO),
		TITULO TEXT NOT NULL, 
		DESCRICAO TEXT,
		DATA_CRIACAO TIMESTAMPTZ NOT NULL,
		DATA_EDICAO TIMESTAMPTZ NOT NULL,
		URL_IMAGEM TEXT,
		FLAG_ARQUIVADO BOOLEAN
);

CREATE TABLE SENAINOTES.NOTAS(
		ID_NOTAS INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		ID_TAG INT NOT NULL REFERENCES SENAINOTES.TAG(ID_TAG),
		ID_ANOTACAO INT NOT NULL REFERENCES SENAINOTES.ANOTACAO(ID_ANOTACAO)
);